# Generated by Django 3.2.9 on 2021-11-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dia', models.DateField()),
                ('pelicula', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
            ],
        ),
    ]
