# Generated by Django 3.2.9 on 2021-11-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='dia',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
