# Generated by Django 3.2.9 on 2021-11-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_venta', '0004_auto_20211115_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.CharField(max_length=4)),
                ('precio', models.FloatField()),
                ('funcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_venta.funcion')),
            ],
        ),
    ]
